### PR TITLE
Add MMM format to allow short month names (e.g. Mar)

### PR DESCRIPTION
**Pull request by peterbell215**

### CODE REVIEW

**Comment by peterbell215** [comment]
Rereading the original request, realise that MMM might be more sensible.  Happy to modify if you feel that would be better.

**Comment by probablykasper** [comment]
I'm following date-fns for the formatting, so MMM is good yeah.

It does neen i18n support added, and autopunctuation/autocompletion should be looked into

**Comment by peterbell215** [comment]
Taken me a lot longer than I expected - partly as Typescript was new to me.  Needed a holiday where I had a few uninterrupted hours to get my head around it all.  It now works across locales.

**Comment by probablykasper** [comment]
Thanks! I fixed some bugs and made changes to how the parsing works

**Review by probablykasper — APPROVED** [review]

**Pull request merged**
