### PR TITLE
Fix parse value when format has not year (MM-dd) 

### PR DESCRIPTION
**Pull request by jorgejaime**

### CODE REVIEW

**Comment by probablykasper** [comment]
https://github.com/probablykasper/date-picker-svelte/pull/106#issuecomment-2499166111

> Could you elaborate on the issue? It seems to work fine for me:

> https://github.com/user-attachments/assets/848f1cf1-bca8-45dd-a2e1-237cd194365f

I should've mentioned, this screen recording is just from https://date-picker-svelte.kasper.space - not from your PR.

**Comment by jorgejaime** [comment]
The issue is when we set the value manually and clean the input. Steps to reproduce:  1. select a value using date picker 2. clean the value manually 3. set the value manually

**Comment by probablykasper** [comment]
Ah I see

**Comment by jorgejaime** [comment]
https://github.com/user-attachments/assets/d9b082f3-a925-4c7e-bbc6-59953f46fe74

**Comment by jorgejaime** [comment]
@probablykasper is it possible to have this fix this week?

**Comment by probablykasper** [comment]
What you're doing with `min` causes the user's value to be overridden.

The issue just that it defaults to 2020 when no year is supplied instead of using the current year, right?

**Comment by jorgejaime** [comment]
Let say, we have a min date 2020-01-01 and max date 2022-12-31 but current year is 2024. These is the reason I am using min date to set basedate

**Comment by probablykasper** [comment]
I don't really see that making sense for most use cases. I'll make it default to the current year

**Comment by probablykasper** [comment]
https://github.com/probablykasper/date-picker-svelte/releases/tag/v2.15.0

**Pull request closed without merging**
