### PR TITLE
fix : After selecting year/month datepicker getting closed in IOS

### PR DESCRIPTION
**Pull request by akshat-angelone057**
In IOS select tag looses focus, since its default behaviour of IOS safari to focus out from select tag once the option is selected.

so here we focus on wrapper div of select tag, this makes wrapper div as the related target in the onFocusOut event, and visible still remains true

### CODE REVIEW

**Comment by akshat-angelone057** [comment]
@probablykasper please have a look at this PR

**Review by probablykasper — CHANGES_REQUESTED** [review]
This messes with the focus behavior:

https://github.com/probablykasper/date-picker-svelte/assets/11315492/39ed7ced-54c2-4c0a-820a-6f72bd847b35

**Comment by akshat-angelone057** [comment]
@probablykasper fixed please check now

**Comment by probablykasper** [comment]
The issue is that the `<select>`'s outline is gone and that it breaks keyboard accessibility. There are also accessibility issues with `<select>` not being focused

**Comment by akshat-angelone057** [comment]
> The issue is that the `<select>`'s outline is gone and that it breaks keyboard accessibility. I think this also is an issue for screen readers if `<select>` isn't focused

got your point let me work on it

**Comment by probablykasper** [comment]
imo it should be looked into if there's a decent way to keep the `<select>` focused

**Comment by akshat-angelone057** [comment]
@probablykasper so i did bit of research like what can be the done to keep select focus but it seems there is no proper way to do it other than using setTimeout.
seems relatedTarget being null is not yet solved in safari Mobile (earlier it was there in firefox too)- https://github.com/facebook/react/issues/2011

there are ways to get relatedTarget but we will have to give tabIndex = "0" to wrapper divs of select tags

can we handle this case specific to iphone and ipad so that existing a11y remain unaffected? because anyways a11y seems broken in the case of iphone and ipad as datepicker itself is closing after selecting month/year

**Comment by probablykasper** [comment]
Yes it can be iOS-specific

**Pull request closed without merging**
