### PR TITLE
Add browseWithoutSelecting prop

### LINKED ISSUE #15: Do not change current selected date when changing month
First of all, let me thank you for a great datepicker.

I've noticed a behavior that seems to me unusual. When the month or year is switched, the new date is immediately selected.

For example, May 5 is currently selected. If we move the calendar forward one month, June 5 will be selected immediately, and so on. In my opinion the date should not be selected unless I explicitly click on the new date in the new month. At least this is how the datepicker works in Google calendar or the classic jQuery UI [datepicker](https://jqueryui.com/datepicker/).

Is it possible to change the behavior of your datepicker, or at least make a setting for this behavior?

### PR DESCRIPTION
**Pull request by probablykasper**
Continuaton of #18, closes #15. I _think_  it's good to go.

cc @e0

### CODE REVIEW

**Comment by probablykasper** [comment]
It's pretty buggy

**Comment by probablykasper** [comment]
Alright managed to fix the bugs I found so far

**Comment by e0** [comment]
Thanks for continuing the work! It seems to work well and solves #15.

The only thing that felt unclear to me was if pressing the arrow keys (without modifier) should update the `value`. I think I made it so that the `value` would not change when `browseWithoutSelecting` is `true` but I think your version is clearer for both the user and the developer. Now the visual indicator for the selected date would always match the `value`. Using the arrow keys to change the date would be an edge case for me anyways and it wasn't originally mentioned in #15 so I think this PR looks good.

**Comment by probablykasper** [comment]
Yeah I think updating the value when using the arrow keys is nice. Thanks for helping improve the date picker! <3

**Pull request merged**
